import Head from "next/head";
import Axios from "Axios";
import ArticlesList from "@/Components/ArticlesList";

export default function Home({ articles }) {
  console.log(articles.title);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <ArticlesList articles={articles} />
    </>
  );
}

export const getStaticProps = async () => {
  const res = await Axios.get(
    "https://jsonplaceholder.typicode.com/posts?_limit=6"
  );
  let articles = res.data;
  console.log(articles);
  return {
    props: {
      articles: articles,
    },
  };
};
